//! The shared passphrase, and the packet encryption it keys.
//!
//! One machine generates a passphrase, everyone else is given it, and from then
//! on those machines are a room: they hear each other and nobody else. It is a
//! walkie-talkie channel, not an account system — no server, no keys to
//! exchange, nothing to log in to.
//!
//! Every packet is sealed with ChaCha20-Poly1305, which does two jobs at once
//! and is the reason a passphrase is worth having:
//!
//!   * **Admission.** A packet that does not authenticate is dropped, so nobody
//!     outside the room can put audio into your speakers or appear in your
//!     roster. A passphrase that only *gated joining* would be worthless — the
//!     tag would be static and anyone sniffing could copy it.
//!   * **Privacy.** The payload is unreadable. Without this, anyone on the LAN
//!     can capture the packets and reassemble the Opus; they need not be running
//!     this app, and nothing in the roster would ever show they were there.
//!
//! With no passphrase set the app runs exactly as before, in the clear. That is
//! a real choice on a network you control, and refusing to start would be worse
//! than warning — but it is stated plainly rather than being the quiet default.

use chacha20poly1305::aead::{Aead, KeyInit, Payload};
use chacha20poly1305::{ChaCha20Poly1305, Key, Nonce};
use sha2::{Digest, Sha256};

/// Bytes added to every packet: a 12-byte nonce and Poly1305's 16-byte tag.
/// At fifty packets a second per recipient this is 1.4 kB/s — nothing next to
/// the 32 kbit/s of audio it protects.
pub const OVERHEAD: usize = 12 + 16;

/// Words a passphrase is built from. Deliberately short, unambiguous and
/// unlikely to be misheard, because this gets read out across a room or typed
/// off a screenshot. No word is a prefix of another.
const WORDS: [&str; 32] = [
    "amber", "anchor", "bison", "bramble", "cedar", "cobalt", "copper", "delta", "ember", "falcon",
    "fern", "flint", "garnet", "harbor", "indigo", "ivory", "jasper", "kestrel", "lantern", "maple",
    "marble", "nectar", "onyx", "opal", "pewter", "quartz", "raven", "saffron", "thistle", "umber",
    "violet", "walnut",
];

/// A fresh passphrase: five words from a 32-word list, so 25 bits… which is not
/// enough on its own, which is why there are also 32 random hex characters
/// after them. The words exist to be *said* — "amber-flint-…" over a desk — and
/// the hex to make guessing hopeless.
///
/// Generated by the app rather than chosen by a person on purpose. A passphrase
/// somebody invents is a passphrase somebody else guesses, and because this one
/// is high-entropy the key can be derived with a plain hash instead of paying
/// for a slow one.
pub fn generate() -> String {
    // Straight from the operating system. Not a seeded PRNG: a guessable room
    // key is worse than none at all, because it looks like protection. If the
    // OS will not give randomness, nothing is returned rather than something
    // predictable.
    let mut bytes = [0u8; 21];
    if getrandom::fill(&mut bytes).is_err() {
        return String::new();
    }
    let words: Vec<&str> = bytes[..5]
        .iter()
        .map(|b| WORDS[(*b as usize) % WORDS.len()])
        .collect();
    let hex: String = bytes[5..].iter().map(|b| format!("{b:02x}")).collect();
    format!("{}-{}", words.join("-"), hex)
}

/// The key, or `None` when no passphrase is set.
///
/// SHA-256 over a domain string and the passphrase. A slow KDF exists to make
/// *weak* passphrases expensive to guess; `generate` produces 128 bits of
/// randomness, so there is nothing here for Argon2 to buy. Anyone typing their
/// own short passphrase is choosing a weaker room, and the app says so.
fn key_of(passphrase: &str) -> Option<[u8; 32]> {
    let p = passphrase.trim();
    if p.is_empty() {
        return None;
    }
    let mut h = Sha256::new();
    h.update(b"zetta-com/room/v1");
    h.update(p.as_bytes());
    Some(h.finalize().into())
}

/// A short code for the room, shown on every machine.
///
/// The point is that a mismatched passphrase must not look like a network
/// fault. Without this, one machine typing the passphrase wrongly is
/// indistinguishable from a switch that dropped it: everything appears to run,
/// and nobody is there. Two people comparing four characters settle it in
/// seconds.
///
/// Derived from the key by hashing it again, so the code itself gives nothing
/// away.
pub fn code(passphrase: &str) -> Option<String> {
    let key = key_of(passphrase)?;
    let mut h = Sha256::new();
    h.update(b"zetta-com/code/v1");
    h.update(key);
    let d = h.finalize();
    Some(
        d[..2]
            .iter()
            .map(|b| format!("{b:02X}"))
            .collect::<String>(),
    )
}

/// Seals and opens packets for one room. Absent when there is no passphrase,
/// and then nothing is encrypted at all.
pub struct Room {
    cipher: ChaCha20Poly1305,
    /// Random per run, so two runs of the same app on the same machine cannot
    /// produce the same nonce for the same key. The counter alone could not
    /// promise that across a restart.
    prefix: [u8; 4],
    counter: std::sync::atomic::AtomicU64,
}

impl Room {
    pub fn new(passphrase: &str) -> Option<Self> {
        let key = key_of(passphrase)?;
        let mut prefix = [0u8; 4];
        getrandom::fill(&mut prefix).ok()?;
        Some(Self {
            cipher: ChaCha20Poly1305::new(&Key::from(key)),
            prefix,
            counter: std::sync::atomic::AtomicU64::new(0),
        })
    }

    /// `header` is authenticated but not encrypted — the receiver needs the
    /// sequence number before it can decide what to do with a packet, and the
    /// jitter buffer reads it before anything is opened. Authenticated so it
    /// still cannot be forged or edited in flight.
    ///
    /// Returns nonce ‖ ciphertext ‖ tag.
    pub fn seal(&self, header: &[u8], payload: &[u8]) -> Option<Vec<u8>> {
        let n = self
            .counter
            .fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let mut nonce = [0u8; 12];
        nonce[..4].copy_from_slice(&self.prefix);
        nonce[4..].copy_from_slice(&n.to_be_bytes());

        let sealed = self
            .cipher
            .encrypt(
                &Nonce::from(nonce),
                Payload {
                    msg: payload,
                    aad: header,
                },
            )
            .ok()?;

        let mut out = Vec::with_capacity(12 + sealed.len());
        out.extend_from_slice(&nonce);
        out.extend_from_slice(&sealed);
        Some(out)
    }

    /// `None` for anything that does not authenticate — a packet from outside
    /// the room, or one that was tampered with. Silence is the correct
    /// response: answering would tell a stranger they found something.
    pub fn open(&self, header: &[u8], body: &[u8]) -> Option<Vec<u8>> {
        if body.len() < 12 {
            return None;
        }
        let (nonce, sealed) = body.split_at(12);
        let nonce: [u8; 12] = nonce.try_into().ok()?;
        self.cipher
            .decrypt(
                &Nonce::from(nonce),
                Payload {
                    msg: sealed,
                    aad: header,
                },
            )
            .ok()
    }
}
